name: CI

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - "*.md"
  merge_group:
    types: [checks_requested]
  pull_request:
    types: [review_requested]
    paths-ignore:
      - "*.md"

jobs:
  tests:
    name: Run Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            go-version: '1.20'
          - os: ubuntu-latest
            go-version: '1.21'
          - os: ubuntu-latest
            go-version: '1.22'
          - os: macos-latest
            go-version: '1.22'
          - os: windows-latest
            go-version: '1.22'
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: go test -v -race -coverprofile="coverage.txt" -covermode=atomic -coverpkg="./wssocks" "./tests"

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.txt
          fail_ci_if_error: true