name: Publish to PyPI

on:
  release:
    types: [released]  # Only trigger when release is published (not draft)

permissions:
  contents: read

jobs:
  publish-to-pypi:
    name: Publish Python Package to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/wssocks
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Install gopy
        run: go install github.com/go-python/gopy@latest

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Set version environment variable
        run: |
          echo "WSSOCKS_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build source distribution
        run: |
          cd bindings/python
          python -m build --sdist --outdir ../../dist

      - name: Verify package
        run: |
          python -m twine check dist/*

      - name: Download artifacts from build job
        uses: actions/download-artifact@v3
        with:
          path: dist/
          pattern: python-wheels-*
          merge-multiple: true

      - name: List all packages
        run: |
          ls -la dist/

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
          verify-metadata: true
          verbose: true