name: Publish to PyPI

on:
  release:
    types: [released]  # Only trigger when release is published (not draft)

permissions:
  contents: read

jobs:
  publish-to-pypi:
    name: Publish Python Package to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/linksocks
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing

    steps:
      - name: Checkout code (for tag context)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Resolve tag commit
        id: tag_commit
        run: |
          echo "sha=$(git rev-list -n 1 ${{ github.event.release.tag_name }})" >> $GITHUB_OUTPUT

      - name: Download Linux wheels from tag workflow
        uses: dawidd6/action-download-artifact@v11
        with:
          workflow: python-tests.yml
          workflow_conclusion: success
          commit: ${{ steps.tag_commit.outputs.sha }}
          name: wheels-linux-x86_64
          path: dist/
          check_artifacts: true
          if_no_artifact_found: error

      - name: Download Linux ARM64 wheels from tag workflow
        uses: dawidd6/action-download-artifact@v11
        with:
          workflow: python-tests.yml
          workflow_conclusion: success
          commit: ${{ steps.tag_commit.outputs.sha }}
          name: wheels-linux-aarch64
          path: dist/
          check_artifacts: true
          if_no_artifact_found: error

      - name: Download source distribution from tag workflow
        uses: dawidd6/action-download-artifact@v11
        with:
          workflow: python-tests.yml
          workflow_conclusion: success
          commit: ${{ steps.tag_commit.outputs.sha }}
          name: source-dist
          path: dist/
          check_artifacts: true
          if_no_artifact_found: error

      - name: List distributions
        run: |
          echo "=== Distribution files ==="
          ls -la dist/
          echo "=== Wheel files ==="
          find dist/ -name "*.whl" -exec ls -la {} \;
          echo "=== Source distribution ==="
          find dist/ -name "*.tar.gz" -exec ls -la {} \;

      - name: Publish distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
          verify-metadata: true
          verbose: true